source("LeaStartup.R", chdir = TRUE)
setwd(file.path(leaconfig$rootdir,"R"))
source("DownsampledTemplates.R", chdir = TRUE)
source("JacobiansSexComparison.R", chdir = TRUE)
source("TtestsSexComparison.R", chdir = TRUE)
